name: CI

on:
  # push:
  #   branches: ["main"]

  # reference: https://docs.github.com/ko/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [TRIGGER_API_TEST]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Get commit id
      id: vars
      run: |
        echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

    - name: echo message from payload
      run: echo "${{ github.event.client_payload.message }}"
